# Generated by Django 5.1.7 on 2025-03-23 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chapters', '0001_initial'),
        ('courses', '0002_alter_course_description_alter_course_name'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='chapter',
            constraint=models.UniqueConstraint(fields=('course', 'chapter_no'), name='unique_course_chapter_no'),
        ),
    ]
