# Generated by Django 4.2.20 on 2025-03-17 12:04

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=255, verbose_name='Course Name')),
                ('description', models.TextField(validators=[django.core.validators.MinLengthValidator(20, 'description must be atleast 20 characters.')], verbose_name='Course Description')),
                ('published_date', models.DateField(blank=True, null=True, verbose_name='Course publish date')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.instructorprofile', verbose_name='Course Author')),
            ],
        ),
    ]
