# Generated by Django 5.1.7 on 2025-03-23 19:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='description',
            field=models.TextField(validators=[django.core.validators.MinLengthValidator(20, 'Description must be atleast 20 characters.')], verbose_name='Course Description'),
        ),
        migrations.AlterField(
            model_name='course',
            name='name',
            field=models.TextField(max_length=255, validators=[django.core.validators.MinLengthValidator(5, 'Course name must be atleast 5 characters.')], verbose_name='Course Name'),
        ),
    ]
